import {
  Zap,
  Smartphone,
  Laptop,
  Tablet,
  Monitor,
  Headphones,
  Bike,
  Car,
  Bicycle,
  Sofa,
  Chair,
  Bed,
  Archive,
  Star,
  Microwave,
  Fridge,
  WashingMachine,
  Snowflake,
  Coffee,
  Shirt,
  Tshirt,
  Footprints, // Giả sử 'Shoe' được thay bằng 'Footprints'
  ShoppingBag, // Giả sử 'Bag' được thay bằng 'ShoppingBag'
  Baby,
  Gift,
  Play,
  Music,
  Joystick,
  Activity,
  Hammer,
  Drill,
  MoreHorizontal,
  Ticket,
  HeartHandshake
} from 'lucide-react'

// Lưu ý: Một số tên icon trong constant.js có thể không tồn tại trong lucide-react.
// Ví dụ: 'TShirt' -> 'Tshirt', 'Shoe' -> 'Footprints', 'Bag' -> 'ShoppingBag'.
// Bạn cần kiểm tra và điều chỉnh cho đúng với thư viện icon bạn dùng.

export const ICONS = {
  Zap,
  Smartphone,
  Laptop,
  Tablet,
  Monitor,
  Headphones,
  Bike,
  Car,
  Bicycle,
  Sofa,
  Chair,
  Bed,
  Archive,
  Star,
  Microwave,
  Fridge,
  WashingMachine,
  Snowflake,
  Coffee,
  Shirt,
  TShirt: Tshirt,
  Shoe: Footprints,
  Bag: ShoppingBag,
  Baby,
  Gift,
  Play,
  Music,
  Joystick,
  Activity,
  Hammer,
  Drill,
  MoreHorizontal,
  Ticket,
  HeartHandshake
}
